FROM golang:alpine as builder
RUN mkdir -p /build
ADD . /build/
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' http-server.go
FROM scratch
EXPOSE 8080
COPY --from=builder /build/http-server /app/
WORKDIR /app
CMD ["./http-server"]
